pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'wahaduzzaman'
        DOCKER_IMAGE_BACKEND = 'plagiarism-backend'
        DOCKER_IMAGE_FRONTEND = 'plagiarism-frontend'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/wahid08034/plagiarism-detector.git'
            }
        }

        stage('Build & Push Docker Images') {
            steps {
                sh 'docker build -t $DOCKERHUB_USER/$DOCKER_IMAGE_BACKEND backend/'
                sh 'docker push $DOCKERHUB_USER/$DOCKER_IMAGE_BACKEND'

                sh 'docker build -t $DOCKERHUB_USER/$DOCKER_IMAGE_FRONTEND frontend/'
                sh 'docker push $DOCKERHUB_USER/$DOCKER_IMAGE_FRONTEND'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}
